#mkdir auth-service
cd auth-service
#mkdir src
mkdir src/domain
mkdir src/application
mkdir src/infrastructure
mkdir src/infrastructure/postgres
mkdir src/interfaces
mkdir src/interfaces/http
mkdir migrations

touch Cargo.toml
touch .env
touch README.md
touch src/main.rs
touch src/lib.rs
touch src/config.rs
touch src/routes.rs
touch src/server.rs
touch src/domain/mod.rs
touch src/domain/user.rs
touch src/domain/errors.rs
touch src/domain/value_objects.rs
touch src/application/mod.rs
touch src/application/services.rs
touch src/application/dto.rs
touch src/application/errors.rs
touch src/infrastructure/mod.rs
touch src/infrastructure/postgres/mod.rs
touch src/infrastructure/postgres/user_repository.rs
touch src/infrastructure/keycloak_client.rs
touch src/infrastructure/email_client.rs
touch src/interfaces/mod.rs
touch src/interfaces/http/handlers.rs
touch src/interfaces/http/errors.rs
touch src/interfaces/openapi.rs 