servers_list = [
    "google.com,Google Apis,TCP,https,Web,10",
    "maps.google.com,Google Apis,TCP,https,Web,10",
    "play.google.com,Google Apis,UDP,Quick,Video,15",
    "drive.google.com,Google Apis,TCP,https,Web,5",
    "apis.google.com,Google Apis,TCP,https,Web,5",
    "mail.google.com,Google Apis,TCP,https,Text,5",
    "accounts.google.com,Google Apis,TCP,https,Text,5",
    "-,-,TCP,https,Web,10",
    "-,-,TCP,https,Text,10",
    "-,-,TCP,https,Video,10",
]

devices = [
    "iphone",
    "iphone 12",
    "iphone 13",
    "iphone 14",
    "iphone 15",
    "iphone 14 pro",
    "iphone 15 pro",
    "samsung",
    "samsung s19",
    "samsung s20",
    "samsung s21",
    "samsung s22",
    "samsung s23",
    "nokia",
    "xioami",
    "pixel",
    "htc",
    "blackberry",
    "motorolla",
]
