CREATE KEYSPACE events WITH replication = {'class':'SimpleStrategy','replication_factor':1};
CREATE TABLE events.events_raw(
    "bucket" text,
    "probeID" text,
    "eventID" text,
    "locationID" text,
    "transactionStart" bigint,
    "transactionEnd" bigint,
    "transactionDuration" bigint,
    "clientIPAddress" text,
    "clientPort" int,
    "serverIPAddress" text,
    "serverPort" int,
    "ipProtocol" text,
    "category" text,
    "bytesFromClient" bigint,
    "bytesToClient" bigint,
    "bytesFromServer" bigint,
    "bytesToServer" bigint,
    "subscriberID" bigint,    
    "applicationProtocol" text,
    "applicationName" text,
    "domain" text,
    "deviceType" text,
    "networkType" text,
    "contentType" text,
    "lostBytesClient" bigint,
    "lostBytesServer" bigint,
    "srttMsClient" bigint,
    "srttMsServer" bigint,        
    PRIMARY KEY (bucket, transactionStart));
